### ISSUE TITLE
Cannot Update to 0.10.2

### ISSUE THREAD

**Issue by wnlowe** [christopherbaine/Canvas-Public#5]
# Details

I am currently on 0.10.1 and when I go `File -> Check for Updates` it says I am on the most recent version. 
![image](https://github.com/christopherbaine/Canvas-Public/assets/43211247/24d5d8ca-a5ab-4d05-b657-cbf69ae1fbc3)
![image](https://github.com/christopherbaine/Canvas-Public/assets/43211247/5d537e33-d519-407f-8f75-3f13c4c0aa55)

# Specs
## OS
* Windows 11
## Canvas Version
* 0.10.1
## Industry Use Case
* N/A

**Comment by wnlowe** [comment]
Manually downloading 0.10.13. Will continue to track issue. MacOS check update from 0.9.x to 0.10.13 did work.

**Comment by christopherbaine** [comment]
Did you accidentally check the "don't check for updates" button at some point?

**Comment by wnlowe** [comment]
Marking as closed due to unreliable hardware, will archive for tracking in case we hear of anybody else with this issue,
